version: '3.1'
services:
  database:
    build:
      context: ./
      dockerfile: docker_images/database/Dockerfile
    ports:
      - "27017:27017"

  restapi:
    build:
      context: ./
      dockerfile: docker_images/rest_api/Dockerfile
    ports:
      - "4000:10010"