swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /messages:
    # binds a127 app logic to a route
    x-swagger-router-controller: Message
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: getMessage
      parameters:
        - name: name
          in: query
          description: The name of the person from which we want to read the secret message.
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/Message"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
            
    post:
      description: Post a secret message to a given name.
      operationId: postMessage
      
      parameters:
        - name: message
          in: body
          description: The name of the person to whom to say hello
          required: true
          schema:
            $ref: "#/definitions/Message"
      produces:
        - text/plain
      responses:
        "201":
            description: Created
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  Message:
    required:
      - message
      - name
    properties:
      message:
        type: string
      name:
        type: string
        
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
